import { useState, useMemo, useEffect, useRef } from "react";
import { App } from "../App";
import { useChat } from "../hooks/use-chat";
import { ChatMessage } from "../components/ChatMessage";
import { appConfig } from "../../config.browser";
import { Welcome } from "../components/Welcome";

import { detectLandmarks } from '../components/vision';
import { syncRecognize } from '../components/speech';


export default function Index() {

  // Obtén las claves de API desde las variables de entorno
  const googleVisionApiKey = process.env.REACT_APP_GOOGLE_VISION_API_KEY;
  const googleSpeechToTextApiKey = process.env.REACT_APP_GOOGLE_SPEECH_TO_TEXT_API_KEY;

  // Estado para almacenar la imagen y el archivo de audio
  const [image, setImage] = useState(null);
  const [audio, setAudio] = useState(null);


  // The content of the box where the user is typing
  const [message, setMessage] = useState<string>("");

  // This hook is responsible for managing the chat and communicating with the
  // backend
  const { currentChat, chatHistory, sendMessage, cancel, state, clear } =
    useChat();

  // This is the message that is currently being generated by the AI
  const currentMessage = useMemo(() => {
    return { content: currentChat ?? "", role: "assistant" } as const;
  }, [currentChat]);

  // This is a ref to the bottom of the chat history. We use it to scroll
  // to the bottom when a new message is added.
  const bottomRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollToBottom();
  }, [currentChat, chatHistory, state]);

  const scrollToBottom = () => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  // This is a ref to the input box. We use it to focus the input box when the
  // user clicks on the "Send" button.
  const inputRef = useRef<HTMLInputElement>(null);
  const focusInput = () => {
    inputRef.current?.focus();
  };

  useEffect(() => {
    focusInput();
  }, [state]);


  // Función para manejar la carga de imágenes
  const handleImageUpload = (file) => {
    // Puedes realizar las operaciones necesarias con la imagen aquí
    setImage(file);

    // Convierte la imagen a base64 (reemplázalo con tu lógica para convertir la imagen a base64)
    const base64Image = await convertirAbase64(file);

    // Llama a detectLandmarks y obtén los textos de los landmarks
    try {
      const texts = await detectLandmarks(base64Image);
      setMessage(texts);
      console.log('Textos de landmarks:', texts);
    } catch (error) {
      console.error('Error al detectar landmarks:', error);
    }
  };
};

// Función para manejar la carga de archivos de audio
const handleAudioUpload = async (file) => {
  // Puedes realizar las operaciones necesarias con el archivo de audio aquí
  setAudio(file);
};

return (
  <App title="TravelMate">
    <main className="bg-white md:rounded-lg md:shadow-md p-6 w-full h-full flex flex-col">
      <section className="overflow-y-auto flex-grow mb-4 pb-8">
        <div className="flex flex-col space-y-4">
          {chatHistory.length === 0 ? (
            <>
              <Welcome />
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {appConfig.samplePhrases.map((phrase) => (
                  <button
                    key={phrase}
                    onClick={() => sendMessage(phrase, chatHistory)}
                    className="bg-gray-100 border-gray-300 border-2 rounded-lg p-4"
                  >
                    {phrase}
                  </button>
                ))}
              </div>
              <div className="flex justify-center">
                <p className="text-sm text-gray-500 mt-5">
                  Built with 🤖{" "}
                  <a
                    className="underline"
                    href="https://github.com/ascorbic/daneel"
                  >
                    Daneel
                  </a>
                </p>
              </div>
            </>
          ) : (
            chatHistory.map((chat, i) => (
              <ChatMessage key={i} message={chat} />
            ))
          )}

          {currentChat ? <ChatMessage message={currentMessage} /> : null}
        </div>

        <div ref={bottomRef} />
      </section>
      <div className="flex items-center justify-center h-20">
        {state === "idle" ? null : (
          <button
            className="bg-gray-100 text-gray-900 py-2 px-4 my-8"
            onClick={cancel}
          >
            Detener generación
          </button>
        )}
      </div>

      <section className="bg-gray-100 rounded-lg p-2">
        <label className="text-gray-700 text-sm font-bold mb-2">
          Carga una imagen
        </label>
        <input
          type="file"
          accept="image/*"
          onChange={(e) => handleImageUpload(e.target.files[0])}
        />

        <label className="ml-2 text-gray-700 text-sm font-bold mb-2">
          Carga un archivo de audio
        </label>
        <input
          type="file"
          accept="audio/*"
          onChange={(e) => handleAudioUpload(e.target.files[0])}
        />
      </section>

      <section className="bg-gray-100 rounded-lg p-2">
        <form
          className="flex"
          onSubmit={(e) => {
            e.preventDefault();
            sendMessage(message, chatHistory);
            setMessage("");
          }}
        >
          {chatHistory.length > 1 ? (
            <button
              className="bg-gray-100 text-gray-600 py-2 px-4 rounded-l-lg"
              type="button"
              onClick={(e) => {
                e.preventDefault();
                clear();
                setMessage("");
              }}
            >
              Limpiar
            </button>
          ) : null}


          <input
            type="text"
            ref={inputRef}
            className="w-full rounded-l-lg p-2 outline-none"
            placeholder={state == "idle" ? "Type your message..." : "..."}
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            disabled={state !== "idle"}
          />
          {state === "idle" ? (
            <button
              className="bg-green-700 text-white font-bold py-2 px-4 rounded-r-lg"
              type="submit"
            >
              Enviar
            </button>
          ) : null}
        </form>
      </section>
    </main>
  </App>
);
}
